spring:
  profiles:
    active: local

#local
---

server:
  profiles: local
  port: 10000

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ENGSTUDYAPP_DB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: engstudyappserver
    password: '0612'
# --- 메모리 디비 사용 시 설정 내용
  #datasource:
  #  url: jdbc:h2:mem:testdb
   # driver-class-name: org.h2.Driver
    #data: classpath:data-h2.sql <- 원래 주석 되어있었음.
    #username: sa
    #password:
# ------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 1000
  #h2:
  #  console:
  #    enabled: true
  jwt:
    # jwt의 secret key.
    secret: englishstudysecretkey!@#

# 배포
---
spring:
  profiles: run
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '0000'
    url: jdbc:mysql://13.125.59.65:3306/EnglishStudyApp?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: englishstudy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  #h2:
    #console:
      #enabled: true
