spring:
  profiles:
    active: local

#local
---

server:
  profiles: local
  port: 10000

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.co1bgasax172.ap-northeast-2.rds.amazonaws.com:3306/engstudyapp_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: englishstudyappserver
    password: '0612'
# --- 메모리 디비 사용 시 설정 내용
  #datasource:
  #  url: jdbc:h2:mem:testdb
   # driver-class-name: org.h2.Driver
    #data: classpath:data-h2.sql <- 원래 주석 되어있었음.
    #username: sa
    #password:
# ------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 1000
  #h2:
  #  console:
  #    enabled: true
  jwt:
    # jwt의 secret key.
    secret: englishstudysecretkey!@#

# 배포
---

server:
  profiles: run
  port: 10000

spring:
  profiles: run

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-englishstudyappapiserver.ckovzyfpq2y1.ap-northeast-2.rds.amazonaws.com:3306/ENGSTUDYAPP_DB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: englishstudyappserver
    password: '0612'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 1000
    #database: mysql
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #generate-ddl: true
    #show-sql: true
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
  #h2:
    #console:
      #enabled: true

  jwt:
    secret: englishstudysecretkey!@#
